---
version: '3.8'
services:
  mongodb:
    image: mongo:5.0.6
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: alterra
    networks:
      - my-network
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - '5432:5432'
    volumes:
      - postgre-data:/var/lib/postgresql/data
    environment:
      # Default user is -> postgres
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: 'SevenEightTwo782' # Change to your unique password
    networks:
      - my-network
  mysql:
    image: mysql:5.7
    restart: always
    container_name: mysql
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql_db:/var/lib/mysql
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq-local'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-log:/var/log/rabbitmq/
    networks:
      - rabbitmq_net
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - cache:/data
volumes:
  mongodb-data:
  mongodb-config:
  postgre-data:
  rabbitmq-log:
  rabbitmq-data:
  mysql_db:
  cache:
    driver: local

networks:
  my-network:
    driver: bridge
  rabbitmq_net:
    driver: bridge